branch-defaults:
  main:
    environment: django-tutorial-dev
environment-defaults:
  django-tutorial-dev:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  default_ec2_keyname: myNewKeys
  default_platform: Python
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
